### ISSUE TITLE
Background script in i3 config?

### ISSUE THREAD

**Issue by bdotsamir** [lucyy-mc/dotfiles-new#1]
Hii! I really like your rice and I wanted to copy it, but I can't find the script you mentioned on this line in your i3 config? Would you mind sharing it please?

https://github.com/lucyy-mc/dotfiles-new/blob/8aa276d6b50b7ff94f60c1fc5327e8589ed901e4/.config/i3/config#L18

**Comment by lucyydotp** [comment]
Really sorry, looks like I forgot to add it. I'll do it as soon as I can, should be no longer than an hour.

**Comment by lucyydotp** [comment]
I've added it.

**Comment by bdotsamir** [comment]
actually on this same thread since i had a brainwave, could this be a cron job?

**Comment by lucyydotp** [comment]
It definitely could be, I just don't have a scheduler on my PC and there eas no point setting one up for such a small job.
